### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sheylaPozo**
This is a solo project built with bootstrap, CSS, and HTML, I hope I can get your review and evaluation of this project. Thank you.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Nice Job here @sheylaPozo 🎉👏👏

You've done quite well on this project, your hard work is commendable.👍🎉

However, there are yet a few changes that need to be made before proceeding:👇
- [x] Kindly fix the search icon position. [Screenshot]👇
ice_screenshot_20200406-192332

- [x] From this project and all other subsequent projects. PLEASE do not close a pull request after a reviewer has commented on it, simply fix the issue on the same pull request and request another review using the SAME PULL REQUEST LINK. Kindly take note of this.

- [x] - Also do ensure your future commit messages are descriptive enough. View this ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) for clarification.

Kindly fix and take note of these issues👆

Once again great job on this.👌

Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by sheylaPozo** [comment]
good morning I have corrected the issues, I kindly ask you for a new review of my project, thanks.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @sheylaPozo 👋

You've made good progress since your last review. 👌👌

However, kindly ensure you take note of this in your next project:

- [x] Do ensure your commits messages are descriptive enough as can be seen in yours the messages are too short and non-descriptive.
ice_screenshot_20200408-194645

- [x] Also fix the HTML5 validation errors using this [tool](https://validator.w3.org/nu/#file)
ice_screenshot_20200408-195125.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**You are almost there.**💪
You've got this👏👏

HAPPY CODING👨‍💻

**Comment by sheylaPozo** [comment]
good afternoon, I finished with the last corrections proposed, I will submit the project to get a new review.

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @sheylaPozo !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

- [x] seems that the search icon is still bad positioned(in Firefox). try to remove the margin left -30, seems that that is the problem. in Chrome is working fine.
Screenshot_2020-04-08 Newsweek - News, Analysis, Politics, Business, Technology

- [x] the HTML markup validator  still giving some errors. 
- [x] I don't see new commits, are you sure you pushed the changes? 


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by sheylaPozo** [comment]
- I fixed the error, I hope this time I get my project approved, thank you for the reviews.

**Review by serdg0 — CHANGES_REQUESTED** [review]
Hi @sheylaPozo :v: 
You are close to the finish line! :100: And the project is looking **very** good!

**Status: Required Changes.**

- [x] Missing alignment in the nav element. The input is not aligned as in the original site. I attach the image below.
Selection_002
 - [x] There are still some errors in the markup validation.

Also, as the previews reviewer said, there are no commits, so maybe you didn't push them?.

Feel free to reach me in slack!

### Happy coding! :computer: 
Sergio Diaz Gonzalez

**Comment by sheylaPozo** [comment]
fixed errors, waiting for a new review, thank you.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @sheylaPozo, you have done a great job 👍 Having fixed all the necessary changes pointed out by the previous TSE's. Our project is now ready to be merged 😄 I hereby approve of the project ✋ Go ahead and merge to master and submit project completion form 🙂 

Good luck with your next projects 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by sheylaPozo** [comment]
Thank you for your reviews :)

**Pull request merged**
